name: categorifier-c
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "ghc8107"
          - "ghc901"
        experimental: [false]
        include:
          - ghc: "ghc921"
            os: ubuntu-latest
            experimental: true
          - ghc: "ghcHEAD"
            os: ubuntu-latest
            experimental: true
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Checkout repositiory code
      uses: actions/checkout@v3
    - name: List files
      run: |
        ls ${{ github.workspace }}
    - name: build
      run: |
        nix build --print-build-logs .#${{ matrix.ghc }}_all || ${{ matrix.experimental }}
  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rwe/actions-hlint-setup@v1
        with:
          version: '3.3.6'
      - uses: rwe/actions-hlint-run@v2
        with:
          path: '["./"]'
          fail-on: status
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v5
